[log]
log_file = 'proxy_downloader.log'
log_level_file = "WARNING"
log_level_console = "INFO"
log_format = "%(asctime)s [%(levelname)s] %(message)s (Process: %(process)s)"
console_log_format = "[%(levelname)s] %(message)s"

[proxy_sources]
all_urls_file = "channel_urls.txt"
output_all_config_file = "configs/proxy_configs_all.json"
allowed_protocols = ["vless://", "tuic://", "hy2://", "ss://"]

[download_settings]
max_retries = 4
retry_delay_base = 2
max_concurrent_channels = 60
max_concurrent_proxies_per_channel = 50
max_concurrent_proxies_global = 50
download_timeout = 15
