log_level_file: WARNING
log_level_console: INFO
log_file: proxy_downloader.log
all_urls_file: channel_urls.txt
output_all_config_file: configs/proxy_configs_all.txt
max_retries: 4
retry_delay_base: 2
max_concurrent_channels: 60
max_concurrent_proxies_per_channel: 50
max_concurrent_proxies_global: 50
download_timeout_sec: 15
allowed_protocols:
  - "vless://"
  - "tuic://"
  - "hy2://"
  - "ss://"
enable_dns_cache: true
