name: Update Proxy Configs

on:
  schedule:
    - cron: '0 */9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SECRET_TOKEN }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up cache for pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p assets
        mkdir -p configs

    - name: Check all_urls.txt exists
      run: |
        if [ ! -f all_urls.txt ]; then
          echo "all_urls.txt не найден. Будет создан пустой файл."
          touch all_urls.txt
        else
          echo "all_urls.txt найден."
        fi

    - name: Run config fetcher script
      run: python src/config.py
      # continue-on-error: true # Раскомментируйте, если хотите останавливать workflow при ошибках в скрипте

    - name: Script execution status
      if: always() # Запустится всегда, даже если предыдущий шаг завершился с ошибкой (если continue-on-error: true)
      run: |
        echo "Python script src/config.py executed."

    - name: Setup Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      id: git_push
      run: |
        git pull --rebase origin main || true
        git add configs/proxy_configs.txt all_urls.txt # all_urls.txt is kept in add command for manual updates
        if ! git diff --staged --quiet; then
          git commit -m "Update proxy configs, stats and reports" # Removed mention of inactive channels
          git push origin HEAD:main
          echo "::set-output name=pushed::true"
          echo "Changes committed and pushed." # Updated message - no mention of all_urls.txt removal
        else
          echo "No changes to commit."
          echo "::set-output name=pushed::false"
        fi
