name: Update Proxy Configs

on:
  schedule:
    - cron: '0 */9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SECRET_TOKEN }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up cache for pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p assets
        mkdir -p configs

    - name: Check scoring_weights.json exists
      run: |
        if [ ! -f configs/scoring_weights.json ]; then
          echo "scoring_weights.json не найден. Будет создан дефолтный файл."
        else
          echo "scoring_weights.json найден."
        fi

    - name: Display scoring_weights.json before script
      if: always() # Запускать даже если предыдущий шаг с проверкой не нашел файл
      run: |
        if [ -f configs/scoring_weights.json ]; then
          echo "Содержимое scoring_weights.json перед запуском скрипта:"
          cat configs/scoring_weights.json
        else
          echo "scoring_weights.json не существует, поэтому содержимое не может быть отображено."
        fi

    - name: Run config fetcher script
      run: python src/config.py
      continue-on-error: true

    - name: Display scoring_weights.json after script
      if: always() # Запускать даже если скрипт завершился с ошибкой (если continue-on-error: true)
      run: |
        if [ -f configs/scoring_weights.json ]; then
          echo "Содержимое scoring_weights.json после запуска скрипта:"
          cat configs/scoring_weights.json
        else
          echo "scoring_weights.json не был создан скриптом (возможно, ошибка)."
        fi

    - name: Setup Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add configs/scoring_weights.json configs/proxy_configs.txt # Убедитесь, что scoring_weights.json тоже добавляется
        git commit --allow-empty -m "Update proxy configs, stats and reports"
        git push
